name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    permissions:
      contents: write
      packages: write

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential git ca-certificates

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo 'source ~/.cargo/env' >> ~/.bashrc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build release
        run: |
          source ~/.cargo/env
          cargo build --release --verbose

      - name: Create archive
        run: |
          mkdir -p dist
          tar -czf dist/svgcleaner_linux_x86_64_${{ github.ref_name }}.tar.gz -C target/release svgcleaner

      - name: Create release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: |
            dist/svgcleaner_linux_x86_64_${{ github.ref_name }}.tar.gz
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}